# Generated by Django 5.1.15 on 2026-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('bucket_s', models.IntegerField(default=60)),
                ('up_bytes', models.BigIntegerField(default=0)),
                ('down_bytes', models.BigIntegerField(default=0)),
                ('up_bps', models.FloatField(default=0.0)),
                ('down_bps', models.FloatField(default=0.0)),
                ('pkts_total', models.IntegerField(default=0)),
                ('pkts_outbound', models.IntegerField(default=0)),
                ('pkts_inbound', models.IntegerField(default=0)),
                ('pkts_internal', models.IntegerField(default=0)),
                ('conn_active_max', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '流量快照',
                'verbose_name_plural': '流量快照',
                'db_table': 'analytics_trafficsnapshot',
                'constraints': [models.UniqueConstraint(fields=('ts', 'bucket_s'), name='uq_snapshot_ts_bucket')],
            },
        ),
    ]
