# Generated by Django 6.0.4 on 2026-05-06 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_id', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('delayed', 'Delayed'), ('dropped', 'Dropped')], db_index=True, max_length=16)),
                ('payload_size', models.PositiveIntegerField()),
                ('event_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_packets', to='topology.networknode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_packets', to='topology.networknode')),
            ],
            options={
                'ordering': ['-event_timestamp', '-id'],
                'indexes': [models.Index(fields=['event_timestamp', 'status'], name='packets_pac_event_t_86b082_idx'), models.Index(fields=['source_node', 'destination_node', 'event_timestamp'], name='packets_pac_source__496e5a_idx')],
            },
        ),
    ]
