# Generated by Django 6.0.4 on 2026-04-24 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('node_type', models.CharField(choices=[('server', 'Server'), ('client', 'Client')], db_index=True, max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='traffic.networknode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='traffic.networknode')),
            ],
            options={
                'ordering': ['source_node__node_id', 'destination_node__node_id'],
                'constraints': [models.UniqueConstraint(fields=('source_node', 'destination_node'), name='unique_network_route'), models.CheckConstraint(condition=models.Q(('source_node', models.F('destination_node')), _negated=True), name='route_source_not_equal_destination')],
            },
        ),
        migrations.CreateModel(
            name='PacketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_id', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('delayed', 'Delayed'), ('dropped', 'Dropped')], db_index=True, max_length=16)),
                ('payload_size', models.PositiveIntegerField()),
                ('event_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_packets', to='traffic.networknode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_packets', to='traffic.networknode')),
            ],
            options={
                'ordering': ['-event_timestamp', '-id'],
                'indexes': [models.Index(fields=['event_timestamp', 'status'], name='traffic_pac_event_t_b9515a_idx'), models.Index(fields=['source_node', 'destination_node', 'event_timestamp'], name='traffic_pac_source__7bddc5_idx')],
            },
        ),
    ]
