# Generated by Codex on 2026-04-24

from django.db import migrations


DEFAULT_NODES = [
    {
        "node_id": "srv_us",
        "name": "Server (Silicon Valley)",
        "ip_address": "8.8.8.8",
        "node_type": "server",
        "latitude": "27.994111",
        "longitude": "120.699341",
        "is_active": True,
    },
    {
        "node_id": "cli_cn",
        "name": "Client (Beijing)",
        "ip_address": "192.168.1.10",
        "node_type": "client",
        "latitude": "39.900000",
        "longitude": "116.400000",
        "is_active": True,
    },
    {
        "node_id": "cli_eu",
        "name": "Client (London)",
        "ip_address": "192.168.1.20",
        "node_type": "client",
        "latitude": "51.500000",
        "longitude": "-0.120000",
        "is_active": True,
    },
    {
        "node_id": "cli_br",
        "name": "Client (Sao Paulo)",
        "ip_address": "192.168.1.30",
        "node_type": "client",
        "latitude": "-23.550000",
        "longitude": "-46.630000",
        "is_active": True,
    },
]


def seed_network_data(apps, schema_editor):
    NetworkNode = apps.get_model("traffic", "NetworkNode")
    NetworkRoute = apps.get_model("traffic", "NetworkRoute")

    nodes = {}
    for payload in DEFAULT_NODES:
        node, _ = NetworkNode.objects.update_or_create(
            node_id=payload["node_id"],
            defaults=payload,
        )
        nodes[node.node_id] = node

    servers = [node for node in nodes.values() if node.node_type == "server"]
    clients = [node for node in nodes.values() if node.node_type == "client"]

    for server in servers:
        for client in clients:
            NetworkRoute.objects.get_or_create(source_node=server, destination_node=client)
            NetworkRoute.objects.get_or_create(source_node=client, destination_node=server)

    for index, server in enumerate(servers):
        for peer in servers[index + 1 :]:
            NetworkRoute.objects.get_or_create(source_node=server, destination_node=peer)
            NetworkRoute.objects.get_or_create(source_node=peer, destination_node=server)


def remove_network_data(apps, schema_editor):
    NetworkRoute = apps.get_model("traffic", "NetworkRoute")
    NetworkNode = apps.get_model("traffic", "NetworkNode")
    node_ids = [payload["node_id"] for payload in DEFAULT_NODES]
    NetworkRoute.objects.filter(source_node__node_id__in=node_ids).delete()
    NetworkRoute.objects.filter(destination_node__node_id__in=node_ids).delete()
    NetworkNode.objects.filter(node_id__in=node_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_network_data, remove_network_data),
    ]
