# Generated by Django 5.1.15 on 2026-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_prefix', models.CharField(db_index=True, max_length=64, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('code', models.CharField(blank=True, default='', max_length=8)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geo 缓存',
                'verbose_name_plural': 'Geo 缓存',
                'db_table': 'network_geolookup',
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('error', 'error')], default='info', max_length=8)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': '系统事件',
                'verbose_name_plural': '系统事件',
                'db_table': 'core_systemevent',
            },
        ),
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.CharField(db_index=True, max_length=24)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('direction', models.CharField(max_length=8)),
                ('protocol', models.CharField(blank=True, default='', max_length=16)),
                ('application', models.CharField(blank=True, default='', max_length=64)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.IntegerField(default=0)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_port', models.IntegerField(default=0)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('nat_forward_addr', models.CharField(blank=True, default='', max_length=64)),
                ('bytes_up', models.BigIntegerField(default=0)),
                ('bytes_down', models.BigIntegerField(default=0)),
                ('pkts', models.IntegerField(default=1)),
                ('src_country', models.CharField(blank=True, default='', max_length=64)),
                ('src_city', models.CharField(blank=True, default='', max_length=64)),
                ('dst_country', models.CharField(blank=True, default='', max_length=64)),
                ('dst_city', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('interface', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name': '连接审计',
                'verbose_name_plural': '连接审计',
                'db_table': 'network_flowrecord',
                'indexes': [models.Index(fields=['direction', 'last_seen'], name='network_flo_directi_365cad_idx'), models.Index(fields=['src_ip', 'last_seen'], name='network_flo_src_ip_83dc52_idx')],
            },
        ),
    ]
