# Generated by Django 5.1.15 on 2026-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolookup',
            options={'verbose_name': 'Geo 归属地', 'verbose_name_plural': 'Geo 归属地'},
        ),
        migrations.AddField(
            model_name='geolookup',
            name='district',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='geolookup',
            name='isp',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='geolookup',
            name='street',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
