# Generated by Django 6.0.4 on 2026-05-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('node_type', models.CharField(choices=[('server', 'Server'), ('client', 'Client')], db_index=True, max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='topology.networknode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='topology.networknode')),
            ],
            options={
                'ordering': ['source_node__node_id', 'destination_node__node_id'],
                'constraints': [models.UniqueConstraint(fields=('source_node', 'destination_node'), name='unique_network_route'), models.CheckConstraint(condition=models.Q(('source_node', models.F('destination_node')), _negated=True), name='route_source_not_equal_destination')],
            },
        ),
    ]
