# Generated by Django 6.0.4 on 2026-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IKuaiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_url', models.TextField(db_index=True)),
                ('login_url', models.TextField()),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('request_mode', models.CharField(max_length=16)),
                ('request_payload', models.JSONField(default=dict)),
                ('upstream_status', models.PositiveIntegerField(blank=True, null=True)),
                ('result_code', models.PositiveIntegerField(blank=True, null=True)),
                ('result_message', models.CharField(blank=True, max_length=255)),
                ('cookies', models.JSONField(default=dict)),
                ('sess_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('cookie_header', models.TextField(blank=True)),
                ('response_headers', models.JSONField(default=dict)),
                ('upstream_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
